name: 🐍 Test application code
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-python:
    name: Run PyTests
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ["ubuntu-22.04", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Tests
        run: |
          pip3 install -r requirements.txt
          cd tests
          ./run_tests.sh -v --junitxml=pytest.xml

      - name: Publish Test Report (for display in workflow UI)
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: "tests/pytest.xml"
          comment_mode: off  # remove to get PR comments on test results. Requires additional repo permissions.
